# Generated by Django 4.2.1 on 2024-01-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_master_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Фрилансер', 'verbose_name_plural': 'Фрилансеры'},
        ),
    ]
