# Generated by Django 4.2.1 on 2024-01-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_portfolio_photos_portfolio_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliophoto',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='skils',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
    ]
